# Generated by Django 5.2.11 on 2026-02-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_studysession_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
